services:
  - type: web
    name: react-code-push
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: MONGODB_URI
        sync: false
    healthCheckPath: /health
    autoDeploy: true
    branch: main
    numInstances: 1
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
    disk:
      name: uploads
      mountPath: /tmp/uploads
      sizeGB: 1 