trigger:
- master

pr:
- master

name: $(Build.SourceBranchName)_$(date:yyyyMMdd)$(rev:.r)

jobs:
- job: BuildAndDeploy
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Install Node.js'

  - script: |
      cd server
      npm install
    displayName: 'Install Dependencies'

  - script: |
      cd server
      npm run build
    displayName: 'Build Server'

  - script: |
      npm pack
      npm install -g react-native-code-push*.tgz
    displayName: 'Package react-native-code-push'
    workingDirectory: $(Build.SourcesDirectory)

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)/server'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      replaceExistingArchive: true
    displayName: 'Archive Server Files'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'drop'
    displayName: 'Publish Build Artifacts'

  - script: |
      curl -X POST "https://api.render.com/deploy/srv-YOUR_SERVICE_ID?key=YOUR_API_KEY"
    displayName: 'Trigger Render.com Deploy'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))