services:
  - type: web
    name: ashish-code-push
    env: node
    plan: free
    buildCommand: |
      cd server
      npm install
    startCommand: |
      cd server
      npm start
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true
    disk:
      name: uploads
      mountPath: /opt/render/project/src/server/uploads
      sizeGB: 1
    github:
      branch: master
      deploy: true
      repo: mailforashish/ashish-code-push
    routes:
      - type: rewrite
        source: /*
        destination: /server 